### ISSUE TITLE
Issue avec les shader

### ISSUE THREAD

**Issue by lferrand** [TsubameDono/Evolution#3]
voici un screen des erreurs que m'envoie unity
si jamais t'as eu quelque chose de similaire @TsubameDono  fais moi signe
![issue toon shader](https://cloud.githubusercontent.com/assets/4314549/11170096/f260d4c2-8bca-11e5-8acf-760903dbe96d.PNG)

**Comment by TsubameDono** [comment]
Essaye d'importer le Package "Effects" dans le menu Assets/Import Packages/Effects

**Comment by lferrand** [comment]
C'est fix :tada:
